### ISSUE TITLE
DrawAt with OverOperator - White border around transparent background image

### ISSUE THREAD

**Issue by justenPalmer** [disintegration/gift#10]
First off, this is a great library. I have been using gift with great results. Props to the author(s).

This issue is in regards to a white border rendered around images with a transparent background when using DrawAt with the OverOperator to write the image onto another image. My intent is to have transparent pngs render with no white border on top of other images.

Is this result the intended functionality of the OverOperator functionality? Is there any strategy I can take to get around this?

Example code below:

```go
package main

import (
	"image"
	"image/color"
	"image/draw"
	"image/png"
	"os"

	"github.com/disintegration/gift"
)

func main() {
	f, err := os.Open("test.png")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	srcImg, _, err := image.Decode(f)
	if err != nil {
		panic(err)
	}

	finalImg := image.NewRGBA(image.Rect(0, 0, 300, 300))

	//draw background color (dk blue) on final image
	bgColor := color.RGBA{0, 0, 100, 255}
	draw.Draw(finalImg, finalImg.Bounds(), &image.Uniform{bgColor}, image.ZP, draw.Src)

	gift.New().DrawAt(finalImg, srcImg, image.Point{0, 0}, gift.OverOperator)

	fOut, err := os.Create("output.png")
	if err != nil {
		panic(err)
	}

	png.Encode(fOut, finalImg)
}
```

Source transparent background png:

![test](https://cloud.githubusercontent.com/assets/1915862/7188448/bcab23aa-e42c-11e4-91e4-3c5a7e46cdfb.png)

Output image:

![output](https://cloud.githubusercontent.com/assets/1915862/7188456/caa39212-e42c-11e4-971b-e94058307397.png)

**Comment by disintegration** [comment]
Hi,
Thank you!

I believe that those white pixels are in your logo image. I used an image editor to do the same thing - place your image over a blue background and I got the same white border. 

Then I used your go code with several test images and there is no white border. The examples are below:

Transparent png image:
![t1](https://cloud.githubusercontent.com/assets/2706839/7190498/58a1c892-e48f-11e4-8ad6-042ac1ceee63.png)

Output image:
![r1](https://cloud.githubusercontent.com/assets/2706839/7190509/71320fd4-e48f-11e4-9835-5db2efaff07d.png)

Transparent png image:
![t2](https://cloud.githubusercontent.com/assets/2706839/7190514/78752cfe-e48f-11e4-90cf-5230c2b94e74.png)

Output image:
![r2](https://cloud.githubusercontent.com/assets/2706839/7190520/7f65e184-e48f-11e4-8ef0-74990d62d3ad.png)

**Comment by justenPalmer** [comment]
Ok that was my fault - I uploaded an image that did have a white edge around it. However, that edge seems to have been created by the gift resize transform.  More specifically, the following:

````go
//get srcImage

g := gift.New(
	gift.Resize(300, 300, gift.LinearResampling),
)
resizedImg := image.NewRGBA(image.Rect(0, 0, 300, 300))
g.Draw(resizedImg, srcImage)

//use DrawAt to place resized image on final image
````

If the image is resized before it is placed on the finalImg using the DrawAt command then there is a white line that appears around the render. However, I got around this by placing the transparent image with the DrawAt command BEFORE the resize was done. This gives me the expected result of no white border.

Thanks so much for your help on this matter.

**Comment by disintegration** [comment]
Then it's probably a bug in the resizing function. Can you upload the image before resizing so I can test and fix it?

**Comment by justenPalmer** [comment]
OK, sure. Here's the code:

````go

package main

import (
	"image"
	"image/color"
	"image/draw"
	"image/png"
	"os"

	"github.com/disintegration/gift"
)

func main() {
	f, err := os.Open("logo.png")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	srcImg, _, err := image.Decode(f)
	if err != nil {
		panic(err)
	}

	g := gift.New(
		gift.Resize(300, 300, gift.LinearResampling),
	)

	resizedImg := image.NewRGBA(image.Rect(0, 0, 300, 300))

	g.Draw(resizedImg, srcImg)

	finalImg := image.NewRGBA(image.Rect(0, 0, 400, 400))

	//draw background color (dk blue) on final image
	bgColor := color.RGBA{0, 0, 100, 255}
	draw.Draw(finalImg, finalImg.Bounds(), &image.Uniform{bgColor}, image.ZP, draw.Src)

	gift.New().DrawAt(finalImg, resizedImg, image.Point{50, 50}, gift.OverOperator)

	fOut, err := os.Create("output.png")
	if err != nil {
		panic(err)
	}

	png.Encode(fOut, finalImg)
}

````

Source image:
![logo](https://cloud.githubusercontent.com/assets/1915862/7196942/67ab31f2-e48f-11e4-936a-c3be5308d9bf.png)

Output image:
![output](https://cloud.githubusercontent.com/assets/1915862/7196947/73ea60d2-e48f-11e4-95db-0288e1d017b8.png)

**Comment by disintegration** [comment]
Now it's fixed. Let me know if you still have this issue.
Thanks a lot for the report!

![output](https://cloud.githubusercontent.com/assets/2706839/7210059/3df9362e-e557-11e4-8722-59263c8587d5.png)

**Comment by justenPalmer** [comment]
It's fixed and looks great! Thanks for your prompt update!
