### ISSUE TITLE
How to add watermark?

### ISSUE THREAD

**Issue by skyleelove** [disintegration/gift#11]
Hi,

   How to add watermark?And how to read a svg image?

**Comment by disintegration** [comment]
Hello,

You can use `DrawAt` method with `OverOperator` to draw a watermark image over another image.  See this examle from the readme:

```go
// Draw the fgImage over the dstImage at the (100, 100) position.
gift.New().DrawAt(dstImage, fgImage, image.Pt(100, 100), gift.OverOperator)
```

SVG is a vector image format, not raster. Not sure if you can load it to `image.Image` in one go. You should probably use some tool first to convert it to png or other raster format.

**Comment by skyleelove** [comment]
Thank you very much!
