### ISSUE TITLE
Feature Request: Thresholding

### ISSUE THREAD

**Issue by saracen** [disintegration/gift#13]
Are there any plans to add thresholding to this library?

I'm completely new to this field, but would be interested in helping out if we can discuss what the API would look like. Any thoughts?

**Comment by disintegration** [comment]
There are no plans, but thresholding can be done relatively easy using the `ColorFunc` filter. See if it fits your use-case.

For example:
```go
g := gift.New(
	gift.ColorFunc(func(r, g, b, a float32) (rr, gg, bb, aa float32) {
		y := 0.299*r + 0.587*g + 0.114*b
		if y > 0.5 {
			return 1, 1, 1, a
		}
		return 0, 0, 0, a
	}),
)
```

Or for the red channel only:

```go
g := gift.New(
	gift.ColorFunc(func(r, g, b, a float32) (rr, gg, bb, aa float32) {
		if r > 0.5 {
			return 1, g, b, a
		}
		return 0, g, b, a
	}),
)
```

As for adding this feature to `gift`, we could provide a user-friendly function, e.g.:
```go
func Threshold(percentage float32) Filter
```
So it can be used this way:
```go
g := gift.New(Threshold(50))
```
Not sure about incorporating more options (channel, black- and white-thresholding).

**Comment by disintegration** [comment]
Implemented: https://github.com/disintegration/gift/commit/be798eb6d9ae04252e124a4a658dbedcae961797
