### ISSUE TITLE
How to save an image to a progressive image?

### ISSUE THREAD

**Issue by AarioAi** [disintegration/gift#15]
How to save an image to a progressive image?

**Comment by disintegration** [comment]
The `gift` package doesn't provide any image encoding/decoding functions, only the image-processing filters and transformations. Typically the standard packages (e.g. image/jpeg or image/png) are used to load or save images. As far as I know the image/jpeg package doesn't have an option to save the progressive type of jpeg. Try looking for a third-party package for this.
