### ISSUE TITLE
Could copyimageFilter be made public/exported?

### ISSUE THREAD

**Issue by saracen** [disintegration/gift#16]
Is there any problem with making this public/exported? It's a handy utility function to use when implementing custom filters.

**Comment by saracen** [comment]
Realised I can easily implement this with something like:
```
func (p *CopyImageFilter) Draw(dst draw.Image, src image.Image, options *Options) {
	draw.Draw(dst, dst.Bounds(), src, image.Point{}, draw.Over)
}
```

Apologies for opening this issue.

**Comment by disintegration** [comment]
You can use the `gift` package itself for image copying (an empty filter list copies src to dst):
```
gift.New().Draw(dst, src)
```
