### ISSUE TITLE
Feature request: trim function

### ISSUE THREAD

**Issue by Gys** [disintegration/gift#18]
See the 'Trim' example in https://images.weserv.nl/#adjustments. It trims "boring" pixels from all edges that contain values within a similarity of the top-left pixel. So the excess of (for example) edged white space is removed. Useful to 'intelligently' crop an image of something against a even coloured background. The resulting image will be smaller but the informational part of the image will not change in any way.

**Comment by disintegration** [comment]
It's a useful function indeed. But I'm not sure how to incorporate it into the package given the current gift's filter design. 

`Filter` interface has the `Bounds` method that calculates a destination image bounds based on the source image bounds. It works well with various transformation functions like rotate or resize, but in this function we need to analyse the pixels to get a new image size.

**Comment by disintegration** [comment]
There is no way to implement the `Bounds` method of the requested filter given the current package API, sorry.
