### ISSUE TITLE
Progressive JPEG defaults to baseline after processing

### ISSUE THREAD

**Issue by thelightstain** [disintegration/gift#21]
Hi, 

I am using gift with [hugo](https://github.com/gohugoio/hugo). It is awesome, but I noticed that all jpegs processed end up as baseline.

Example:
 - original image:
![image](https://user-images.githubusercontent.com/22097179/67550355-f1cf2c80-f70e-11e9-81cb-9d2472dc64cb.png)

- same image resized by hugo via [gift](https://github.com/disintegration/gift):
![image](https://user-images.githubusercontent.com/22097179/67550605-8f2a6080-f70f-11e9-9dba-2f3f7eb35217.png)

The tool used above can be found [here](http://techslides.com/demos/progressive-test.html).

Can this behavior be adjusted so that a progressive jpeg stays progressive after resize/filter?

Thank you!

**Comment by disintegration** [comment]
Hi, 

The gift package does not provide any image decoding/encoding functionality.
 
I believe hugo uses the standard image/jpeg package to encode jpeg images. As far as I know it does not support progressive jpeg enconding.
