### ISSUE TITLE
Animated GIF transparency issue

### ISSUE THREAD

**Issue by paddycarey** [disintegration/gift#9]
Hi, I wasn't sure where the best place to post this was since I'm not sure if it's a bug or if I'm just doing something silly. If this is the wrong forum I apologise.

I've been working on a little HTTP API that builds on gift (https://github.com/paddycarey/ims) and it's working great for PNG and JPEG images, but I've run into an issue when applying filters to animated GIF images. It seems that transparency is not preserved in the filtered frames and it results in large black areas that should really be transparent since they haven't changed since the previous frame.

This is maybe easier to explain with an example.

```go
package main

import (
	"fmt"
	"image"
	"image/gif"
	"os"
	"runtime"

	"github.com/disintegration/gift"
)

func main() {

	runtime.GOMAXPROCS(runtime.NumCPU())

	f, err := os.Open("test.gif")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	g, err := gif.DecodeAll(f)
	if err != nil {
		panic(err)
	}

	filter := gift.New(
		gift.FlipHorizontal(),
	)

	newImages := []*image.Paletted{}
	for _, i := range g.Image {
		dst := image.NewPaletted(filter.Bounds(i.Bounds()), i.Palette)
		filter.Draw(dst, i)
		newImages = append(newImages, dst)
	}
	g.Image = newImages

	of, err := os.Create("out.gif")
	if err != nil {
		panic(err)
	}
	defer of.Close()

	err = gif.EncodeAll(of, g)
	if err != nil {
		panic(err)
	}

	fmt.Println("Successfully encoded gif: out.gif")
}
```

Used with the following test image: 
![test](https://cloud.githubusercontent.com/assets/164309/6926409/f351d594-d7dd-11e4-89a2-c568840683fd.gif)

Produces the following output: 
![out](https://cloud.githubusercontent.com/assets/164309/6926420/0556c790-d7de-11e4-85d2-33eb1fb66716.gif)

I looked around and found some similar issues, I thought it may be the same as [this issue](https://github.com/golang/go/issues/7993), it's certainly got the same symptoms, but I'm not sure. I'm able to run `DecodeAll` and `EncodeAll` and the result will be fine, provided I don't use gift. For what it's worth I also tested with [imaging](https://github.com/disintegration/imaging) and it has the same issue. 

`go version` returns `go1.4.1 linux/amd64` if that helps.

Thanks again for the great library, any help you could provide would be greatly appreciated.

**Comment by disintegration** [comment]
Hi, 

I must say, I'm not a GIF expert. But as far as I know, you're right - when highly optimized (as in your example), each of GIF frames can be just a small part of image that changed since the previous frame. In Go, the unmodified pixels are transparent. I think that paletted image + transparent pixels lead to these artifacts. I think Go image.Paletted ignores the alpha channel in some way when setting pixels. I'm not sure about that. Here's a simple example:

```go
package main

import (
	"fmt"
	"image"
	"image/draw"
	"image/gif"
	"os"
	"runtime"
)

func main() {

	runtime.GOMAXPROCS(runtime.NumCPU())

	f, err := os.Open("test.gif")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	g, err := gif.DecodeAll(f)
	if err != nil {
		panic(err)
	}

	for i := range g.Image {
		clone := image.NewPaletted(g.Image[i].Bounds(), g.Image[i].Palette)
		draw.Draw(clone, clone.Bounds(), g.Image[i], g.Image[i].Bounds().Min, draw.Src)
		g.Image[i] = clone
	}

	of, err := os.Create("out.gif")
	if err != nil {
		panic(err)
	}
	defer of.Close()

	err = gif.EncodeAll(of, g)
	if err != nil {
		panic(err)
	}

	fmt.Println("Successfully encoded gif: out.gif")
}
```

I used the standard image/draw package to create a copy of each frame and saved the copied image. I got the same artifacts. 

The workaround can be restoring the full image for each frame before processing:

```go
package main

import (
	"fmt"
	"image"
	"image/gif"
	"os"
	"runtime"

	"github.com/disintegration/gift"
)

func main() {

	runtime.GOMAXPROCS(runtime.NumCPU())

	f, err := os.Open("test.gif")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	g, err := gif.DecodeAll(f)
	if err != nil {
		panic(err)
	}

	filter := gift.New(
		gift.FlipHorizontal(),
	)

	tmp := image.NewNRGBA(g.Image[0].Bounds())
	for i := range g.Image {
		gift.New().DrawAt(tmp, g.Image[i], g.Image[i].Bounds().Min, gift.OverOperator)
		dst := image.NewPaletted(filter.Bounds(tmp.Bounds()), g.Image[i].Palette)
		filter.Draw(dst, tmp)
		g.Image[i] = dst
	}

	of, err := os.Create("out.gif")
	if err != nil {
		panic(err)
	}
	defer of.Close()

	err = gif.EncodeAll(of, g)
	if err != nil {
		panic(err)
	}

	fmt.Println("Successfully encoded gif: out.gif")
}
```

Here I used gift DrawAt method to draw each frame over previous before processing (the latest version of gift needed, this method was added just a few days ago). I got a better-looking result, but still not ideal. And as go gif package probably don't do such frame optimizations during encoding, the file is larger considerably.  I'll try to find a better solution when I have more time.

**Comment by disintegration** [comment]
Here's another test:

http://play.golang.org/p/XfSiDK4EZj
```go
package main

import (
	"fmt"
	"image"
	"image/color"
)

func main() {
	img := image.NewPaletted(
		image.Rect(0, 0, 1, 1),
		color.Palette{
			color.RGBA{0, 0, 0, 255}, // opaque black
			color.RGBA{0, 0, 0, 0},   // transparent
		},
	)

	img.Set(0, 0, color.RGBA{0, 0, 0, 0}) // set pixel to transparent color
	fmt.Println(img.At(0, 0))             // but got black: {0 0 0 255}
}
```

The test image has two colors in the palette - black and fully transparent color. But, when using the Set method with a transparent color, the pixel actually sets to black. That's how Paletted images work, at least for now. 

Maybe I can add a workaround to the gift package, I just need to figure out the best way.

**Comment by disintegration** [comment]
I've found a similar open issue in Go repository:
https://github.com/golang/go/issues/9902

**Comment by disintegration** [comment]
Latest commit (https://github.com/disintegration/gift/commit/e0c44423676e3610cba4ac8c15e60cdd419eb3da) fixes the issue.

When using simple filters with no pixel blending (flipping, rotating 90, 180 degrees, resizing and rotating using nearest neighbour algorithms), frames with transparency can be used:

```go
package main

import (
	"fmt"
	"image"
	"image/color"
	"image/gif"
	"os"
	"runtime"

	"github.com/disintegration/gift"
)

func main() {

	runtime.GOMAXPROCS(runtime.NumCPU())

	f, err := os.Open("test.gif")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	g, err := gif.DecodeAll(f)
	if err != nil {
		panic(err)
	}

	filter := gift.New(
		gift.ResizeToFit(200, 200, gift.NearestNeighborResampling),
		gift.Rotate(45, color.White, gift.NearestNeighborInterpolation),
	)

	firstFrame := g.Image[0]
	for i := range g.Image {
		// tmp image is used here to keep the same dimensions for each frame
		tmp := image.NewNRGBA(firstFrame.Bounds())
		gift.New().DrawAt(tmp, g.Image[i], g.Image[i].Bounds().Min, gift.CopyOperator)
		dst := image.NewPaletted(filter.Bounds(tmp.Bounds()), g.Image[i].Palette)
		filter.Draw(dst, tmp)
		g.Image[i] = dst
	}

	of, err := os.Create("out.gif")
	if err != nil {
		panic(err)
	}
	defer of.Close()

	err = gif.EncodeAll(of, g)
	if err != nil {
		panic(err)
	}

	fmt.Println("Successfully encoded gif: out.gif")
}
```
![out](https://cloud.githubusercontent.com/assets/2706839/6998784/a711844c-dbf5-11e4-8e7e-407f1d15b941.gif)


But for more complex filters that use pixels mixing, you will still need to restore the full image for each frame by drawing current frame over previous:

```go
package main

import (
	"fmt"
	"image"
	"image/color"
	"image/gif"
	"os"
	"runtime"

	"github.com/disintegration/gift"
)

func main() {

	runtime.GOMAXPROCS(runtime.NumCPU())

	f, err := os.Open("test.gif")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	g, err := gif.DecodeAll(f)
	if err != nil {
		panic(err)
	}

	filter := gift.New(
		// high-quality resampling with pixel mixing
		gift.ResizeToFit(200, 200, gift.LanczosResampling),
		gift.Rotate(45, color.White, gift.LinearInterpolation),
	)

	firstFrame := g.Image[0]
	tmp := image.NewNRGBA(firstFrame.Bounds())
	for i := range g.Image {
		// draw current frame over previous:
		gift.New().DrawAt(tmp, g.Image[i], g.Image[i].Bounds().Min, gift.OverOperator)
		dst := image.NewPaletted(filter.Bounds(tmp.Bounds()), g.Image[i].Palette)
		filter.Draw(dst, tmp)
		g.Image[i] = dst
	}

	of, err := os.Create("out2.gif")
	if err != nil {
		panic(err)
	}
	defer of.Close()

	err = gif.EncodeAll(of, g)
	if err != nil {
		panic(err)
	}

	fmt.Println("Successfully encoded gif: out2.gif")
}
```

![out2](https://cloud.githubusercontent.com/assets/2706839/6998797/f1491232-dbf5-11e4-98b8-ddda76027b32.gif)

**Comment by paddycarey** [comment]
Wow, this is great :)

I've upgraded my local copy and tweaked the code using your examples above, all is working great now. Thanks for the quick response, I really appreciate it. And thanks again for the great library.

**Comment by disintegration** [comment]
You're welcome!

**Comment by huumn** [comment]
Should this code still work or has the API changed? For me, the frames resize but the overall image itself maintains its size like the following (there's a large transparent border on the right and bottom):
![thumb](https://user-images.githubusercontent.com/34140557/39333478-e12fa93a-495f-11e8-8062-b6db5b0e967c.gif)

**Comment by machmum** [comment]
> Should this code still work or has the API changed? For me, the frames resize (and transform) but the overall image itself maintains its size like the following (there's a large transparent border on the right and bottom):
> ![out2](https://user-images.githubusercontent.com/34140557/39333694-9e01f2ac-4960-11e8-83b8-5fab235e2b27.gif)

Using code above, I'm also experiencing this, as the resulted image has the original image size

**Comment by disintegration** [comment]
Something have changed in the `gif` package's logic probably. Unfortunately, I don't have enough time to discover the issue and find the best way to deal with animated gifs now. Looks like the issue is that the Config struct of the GIF still contains the old image size after transformation. Try adding this line just after the `for` loop, before saving the image:

```go
g.Config = image.Config{}
```

This will reset the GIF's config and force it to use the first frame's dimensions on save.
